# Nombre interno de la aplicación Spring Boot.
spring.application.name=biblioteca-api

# Cadena de conexión a MongoDB Atlas; reemplaza usuario, contraseña y cluster por tus datos reales.
spring.data.mongodb.uri=mongodb://localhost:27017/biblioteca

# Nombre de la base de datos usada por la API.
spring.data.mongodb.database=biblioteca

# Puerto local donde se ejecutará la API REST.
server.port=8080

# Muestra mensajes de error claros durante el desarrollo.
server.error.include-message=always
